# Generated by Django 4.0.3 on 2022-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notifications_channel",
            field=models.CharField(default="3764MLL6U5", max_length=10),
        ),
    ]
