# Generated by Django 4.0.3 on 2022-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_email_reset",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
