# Generated by Django 4.0.3 on 2022-03-26 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="activation_mail_sent",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 3, 26, 16, 49, 16, 499148, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.useravatar",
            ),
        ),
    ]
