# Generated by Django 4.0.3 on 2022-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_last_email_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="graduation_year",
            field=models.CharField(default=2022, max_length=4),
            preserve_default=False,
        ),
    ]
