# Generated by Django 4.0.3 on 2022-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_notifications_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_channel',
            field=models.CharField(default='2Q7FFKPBPI', max_length=10),
        ),
    ]
