# Generated by Django 4.0.3 on 2022-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_notifications_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_channel',
            field=models.CharField(default='70ZK7Y1L3C', max_length=10),
        ),
    ]
