# Generated by Django 4.0.3 on 2022-03-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_year',
        ),
    ]
