# Generated by Django 4.0.3 on 2022-03-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_activation_mail_sent_user_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ea_games_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="epic_games_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="ps_network_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="riot_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
