# Generated by Django 4.0.3 on 2022-05-07 15:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_notifications_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_channel',
            field=models.CharField(default=users.models.create_notification_channel, max_length=10),
        ),
    ]
