# Generated by Django 4.0.3 on 2022-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_school_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_channel",
            field=models.CharField(default="8Y6HMDZ3YV", max_length=10),
        ),
    ]
