# Generated by Django 4.0.3 on 2022-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_ea_games_id_user_epic_games_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="school_email",
            field=models.EmailField(max_length=254),
        ),
    ]
