# Generated by Django 4.0.3 on 2022-04-22 16:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_notifications_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="xbox_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="notifications_channel",
            field=models.CharField(
                default=users.models.create_notification_channel, max_length=10
            ),
        ),
    ]
