# Generated by Django 4.0.3 on 2022-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_notifications_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notifications_channel",
            field=models.CharField(default="4I0059QA61", max_length=10),
        ),
    ]
