# Generated by Django 4.0.3 on 2022-03-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_channel',
            field=models.CharField(default='16HSP5AH5F', max_length=10),
        ),
    ]
