# Generated by Django 4.0.3 on 2022-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_notifications_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notifications_channel",
            field=models.CharField(default="5GF6L7L0QB", max_length=10),
        ),
    ]
