# Generated by Django 4.0.3 on 2022-04-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_notifications_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_channel',
            field=models.CharField(default='30ANJB5UI9', max_length=10),
        ),
    ]
