# Generated by Django 4.0.3 on 2022-03-27 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentteammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="platforms",
            field=models.ManyToManyField(to="tournaments.tournamentplatform"),
        ),
    ]
