# Generated by Django 4.0.3 on 2022-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="platform",
        ),
        migrations.AddField(
            model_name="tournament",
            name="platforms",
            field=models.ManyToManyField(to="tournaments.tournamentplatform"),
        ),
    ]
