# Generated by Django 4.0.3 on 2022-03-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentteam",
            name="group_score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TournamentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teams", models.ManyToManyField(to="tournaments.tournamentteam")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
