# Generated by Django 4.0.3 on 2022-04-18 14:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentteam_tournament_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(upload_to='tournaments/7482f74c-f4cf-4bb4-9ae5-d605023f8c3f'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='playoff_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), blank=True, null=True, size=8),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='chat_channel',
            field=models.CharField(default='1F3DD4EG0GC7271', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='contest_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_result/4764ff9f-29e2-41aa-9735-24a76620eddb'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
