# Generated by Django 4.0.3 on 2022-03-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_tournamentteam_group_score_tournamentgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("playoff", "Playoff"), ("group", "Group")],
                        max_length=20,
                    ),
                ),
                ("match_start", models.DateTimeField()),
                ("is_contested", models.BooleanField(blank=True, null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.tournamentteam",
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
    ]
