# Generated by Django 4.0.3 on 2022-03-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_remove_tournament_platform_tournament_platforms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentteam",
            old_name="team_name",
            new_name="name",
        ),
    ]
