# Generated by Django 4.0.3 on 2022-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_tournamentmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmatch",
            name="contest_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
