# Generated by Django 4.0.3 on 2022-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_tournamentmatch_is_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmatch",
            name="is_contested",
            field=models.BooleanField(default=False),
        ),
    ]
