# Generated by Django 4.0.3 on 2022-05-07 15:50

from django.db import migrations, models
import django.db.models.deletion
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_logo_alter_tournament_playoff_array_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='place_finished',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
