# Generated by Django 4.0.3 on 2022-03-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_tournamentmatch_contest_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentteam",
            name="losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
