# Generated by Django 4.0.3 on 2022-03-30 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0004_alter_tournamentmatch_is_contested"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmatch",
            name="round_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentteam",
            unique_together={("captain", "tournament")},
        ),
    ]
