# Generated by Django 4.0.3 on 2022-05-12 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tournaments.models
import tournaments.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_gamertagchoice_tournamentgame_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="match_logo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
