# Generated by Django 4.0.3 on 2022-04-02 21:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournamentmatch_chat_channel_alter_tournament_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='playoff_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=8),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(upload_to='tournaments/98d927aa-7558-4f55-a1f9-69f346cd0af8'),
        ),
        migrations.AlterField(
            model_name='tournamentgroup',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_groups', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='chat_channel',
            field=models.CharField(default='24IQ5ZDQJUTWTIW', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='contest_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_result/9bf72cae-2f0d-4c54-aa50-e20dd74555ff'),
        ),
    ]
